"""Date (isoformat)"""
scalar Date

type Query {
  users(bornAfter: Date = null): [User!]!
}

type User {
  id: Int!
  username: String!
  isOnline: Boolean!
  birthday: Date!
  friends(onlineOnly: Boolean! = false): [User!]!
}